In [25]:
import pandas as pd
import numpy as np

In [26]:
import math
from sklearn import linear_model

In [27]:
#You are at a Pokemon black market planning to buy a Pokemon for battle. 
#All Pokemon are sold at the same price and you can only afford to buy one. 
#You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either Type 1 or Type 2. 
#Which type should you choose in order to maximize your chance of receiving a good Pokemon

In [28]:
#HP, Attack, Defense, Sp. Atk, Sp. Def, and Speed.

In [29]:
Pokemon = pd.read_csv('Pokemon.csv') 

In [85]:
Pokemon.head(60)


#                       Name    Type 1  Type 2  Total   HP  Attack  \
0    1                  Bulbasaur     Grass  Poison    318   45      49   
1    2                    Ivysaur     Grass  Poison    405   60      62   
2    3                   Venusaur     Grass  Poison    525   80      82   
3    3      VenusaurMega Venusaur     Grass  Poison    625   80     100   
4    4                 Charmander      Fire     NaN    309   39      52   
5    5                 Charmeleon      Fire     NaN    405   58      64   
6    6                  Charizard      Fire  Flying    534   78      84   
7    6  CharizardMega Charizard X      Fire  Dragon    634   78     130   
8    6  CharizardMega Charizard Y      Fire  Flying    634   78     104   
9    7                   Squirtle     Water     NaN    314   44      48   
10   8                  Wartortle     Water     NaN    405   59      63   
11   9                  Blastoise     Water     NaN    530   79      83   
12   9    BlastoiseMega Blastoise     Water     NaN    630   79     103   
13  10                   Caterpie       Bug     NaN    195   45      30   
14  11                    Metapod       Bug     NaN    205   50      20   
15  12                 Butterfree       Bug  Flying    395   60      45   
16  13                     Weedle       Bug  Poison    195   40      35   
17  14                     Kakuna       Bug  Poison    205   45      25   
18  15                   Beedrill       Bug  Poison    395   65      90   
19  15      BeedrillMega Beedrill       Bug  Poison    495   65     150   
20  16                     Pidgey    Normal  Flying    251   40      45   
21  17                  Pidgeotto    Normal  Flying    349   63      60   
22  18                    Pidgeot    Normal  Flying    479   83      80   
23  18        PidgeotMega Pidgeot    Normal  Flying    579   83      80   
24  19                    Rattata    Normal     NaN    253   30      56   
25  20                   Raticate    Normal     NaN    413   55      81   
26  21                    Spearow    Normal  Flying    262   40      60   
27  22                     Fearow    Normal  Flying    442   65      90   
28  23                      Ekans    Poison     NaN    288   35      60   
29  24                      Arbok    Poison     NaN    438   60      85   
30  25                    Pikachu  Electric     NaN    320   35      55   
31  26                     Raichu  Electric     NaN    485   60      90   
32  27                  Sandshrew    Ground     NaN    300   50      75   
33  28                  Sandslash    Ground     NaN    450   75     100   
34  29                   Nidoran♀    Poison     NaN    275   55      47   
35  30                   Nidorina    Poison     NaN    365   70      62   
36  31                  Nidoqueen    Poison  Ground    505   90      92   
37  32                   Nidoran♂    Poison     NaN    273   46      57   
38  33                   Nidorino    Poison     NaN    365   61      72   
39  34                   Nidoking    Poison  Ground    505   81     102   
40  35                   Clefairy     Fairy     NaN    323   70      45   
41  36                   Clefable     Fairy     NaN    483   95      70   
42  37                     Vulpix      Fire     NaN    299   38      41   
43  38                  Ninetales      Fire     NaN    505   73      76   
44  39                 Jigglypuff    Normal   Fairy    270  115      45   
45  40                 Wigglytuff    Normal   Fairy    435  140      70   
46  41                      Zubat    Poison  Flying    245   40      45   
47  42                     Golbat    Poison  Flying    455   75      80   
48  43                     Oddish     Grass  Poison    320   45      50   
49  44                      Gloom     Grass  Poison    395   60      65   
50  45                  Vileplume     Grass  Poison    490   75      80   
51  46                      Paras       Bug   Grass    285   35      70   
52  47                   Paras

In [31]:
#Problem Solving Iteration 1

In [32]:
#HP, Attack, Defense, Sp. Atk, Sp. Def, and Speed
#What is the formula to compute Total?
#Does the formula work for all pokemon?

In [33]:
def hypothesis_total (xtotal):
    if xtotal['Total']==xtotal['HP']+xtotal['Attack']+xtotal['Defense']+xtotal['Sp. Atk']+xtotal['Sp. Def']+xtotal['Speed']:
         return 'TRUE'
    else:
        return 'FALSE'
    
Pokemon['hypothesis_total']=Pokemon.apply(hypothesis_total,axis=1)



In [34]:
Pokemon['hypothesis_total'].value_counts()
#800 rows (see also Pokemon.head)
#Check column hypothesis_total --> TRUE (for every Pokemon)

TRUE    800
Name: hypothesis_total, dtype: int64

In [35]:
#Problem Solving Iteration 2

In [36]:
Pokemon_type1=Pokemon[['Type 1']]

In [37]:
Pokemon_type2=Pokemon[['Type 2']]

In [ ]:
#In addition, keep in mind that Type 1 always has a value but Type 2 is sometimes empty (having the NaN value).

In [41]:
Pokemon_type2.isna().sum()

Type 2    386
dtype: int64

In [45]:
round(Pokemon_type2.isna().sum()/len(Pokemon_type2),4)*100
# 0 values 

Type 2    48.25
dtype: float64

In [43]:
from sklearn.preprocessing import OneHotEncoder

In [74]:
from sklearn.preprocessing import OneHotEncoder
encoder_type1 = OneHotEncoder().fit(Pokemon_type1)
print(encoder_type1.categories_)
encoded = encoder_type1.transform(Pokemon_type1).toarray()
print(encoded)
onehot_encoded_type1 = pd.DataFrame(encoded,columns=encoder_type1.categories_)
onehot_encoded_type1.head()

[array(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Bug Dark Dragon Electric Fairy Fighting Fire Flying Ghost Grass Ground  \
0  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0    0.0   
1  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0    0.0   
2  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0    0.0   
3  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0    0.0   
4  0.0  0.0    0.0      0.0   0.0      0.0  1.0    0.0   0.0   0.0    0.0   

   Ice Normal Poison Psychic Rock Steel Water  
0  0.0    0.0    0.0     0.0  0.0   0.0   0.0  
1  0.0    0.0    0.0     0.0  0.0   0.0   0.0  
2  0.0    0.0    0.0     0.0  0.0   0.0   0.0  
3  0.0    0.0    0.0     0.0  0.0   0.0   0.0  
4  0.0    0.0    0.0     0.0  0.0   0.0   0.0

In [75]:
from sklearn.preprocessing import OneHotEncoder
encoder_type2 = OneHotEncoder().fit(Pokemon_type2)
print(encoder_type2.categories_)
encoded = encoder_type2.transform(Pokemon_type2).toarray()
print(encoded)
onehot_encoded_type2 = pd.DataFrame(encoded,columns=encoder_type2.categories_)
onehot_encoded_type2.head()

[array(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water', nan], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


Bug Dark Dragon Electric Fairy Fighting Fire Flying Ghost Grass Ground  \
0  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
1  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
2  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
3  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
4  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   

   Ice Normal Poison Psychic Rock Steel Water  NaN  
0  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
1  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
2  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
3  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
4  0.0    0.0    0.0     0.0  0.0   0.0   0.0  1.0

In [81]:
mean_median_home_value = onehot_encoded_type2.mean()

In [84]:
onehot_encoded_type2.head(60)

Bug Dark Dragon Electric Fairy Fighting Fire Flying Ghost Grass Ground  \
0   0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
1   0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
2   0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
3   0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
4   0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
5   0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
6   0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
7   0.0  0.0    1.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
8   0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
9   0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
10  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
11  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
12  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
13  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
14  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
15  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
16  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
17  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
18  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
19  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
20  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
21  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
22  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
23  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
24  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
25  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
26  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
27  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
28  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
29  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
30  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
31  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
32  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
33  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
34  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
35  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
36  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    1.0   
37  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
38  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
39  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    1.0   
40  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
41  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
42  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
43  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
44  0.0  0.0    0.0      0.0   1.0      0.0  0.0    0.0   0.0   0.0    0.0   
45  0.0  0.0    0.0      0.0   1.0      0.0  0.0    0.0   0.0   0.0    0.0   
46  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
47  0.0  0.0    0.0      0.0   0.0      0.0  0.0    1.0   0.0   0.0    0.0   
48  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
49  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0    0.0   
50  0.0  0.0    0.0      0

In [87]:
onehot_encoded_type2.isna().sum()

Bug         0
Dark        0
Dragon      0
Electric    0
Fairy       0
Fighting    0
Fire        0
Flying      0
Ghost       0
Grass       0
Ground      0
Ice         0
Normal      0
Poison      0
Psychic     0
Rock        0
Steel       0
Water       0
NaN         0
dtype: int64

In [88]:
Overview_type1_type2 = pd.concat([onehot_encoded_type1, onehot_encoded_type2], axis=1)

In [89]:
Overview_type1_type2

Bug Dark Dragon Electric Fairy Fighting Fire Flying Ghost Grass  ...  \
0    0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0  ...   
1    0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0  ...   
2    0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0  ...   
3    0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   1.0  ...   
4    0.0  0.0    0.0      0.0   0.0      0.0  1.0    0.0   0.0   0.0  ...   
..   ...  ...    ...      ...   ...      ...  ...    ...   ...   ...  ...   
795  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0  ...   
796  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0  ...   
797  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0  ...   
798  0.0  0.0    0.0      0.0   0.0      0.0  0.0    0.0   0.0   0.0  ...   
799  0.0  0.0    0.0      0.0   0.0      0.0  1.0    0.0   0.0   0.0  ...   

    Grass Ground  Ice Normal Poison Psychic Rock Steel Water  NaN  
0     0.0    0.0  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
1     0.0    0.0  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
2     0.0    0.0  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
3     0.0    0.0  0.0    0.0    1.0     0.0  0.0   0.0   0.0  0.0  
4     0.0    0.0  0.0    0.0    0.0     0.0  0.0   0.0   0.0  1.0  
..    ...    ...  ...    ...    ...     ...  ...   ...   ...  ...  
795   0.0    0.0  0.0    0.0    0.0     0.0  0.0   0.0   0.0  0.0  
796   0.0    0.0  0.0    0.0    0.0     0.0  0.0   0.0   0.0  0.0  
797   0.0    0.0  0.0    0.0    0.0     0.0  0.0   0.0   0.0  0.0  
798   0.0    0.0  0.0    0.0    0.0     0.0  0.0   0.0   0.0  0.0  
799   0.0    0.0  0.0    0.0    0.0     0.0  0.0   0.0   1.0  0.0  

[800 rows x 37 columns]

In [ ]:
# Problem Solving Iteration 3
# calculate the correlation of Total to each of the encoded fields. 
# Rank the correlations and identify the #1 pokemon type that is most likely to have the highest Total.

In [ ]:
Total=Pokemon['Total']


In [ ]:
Total.head(5)

In [ ]:
check_correlations=pd.concat([Overview_type1_type2,Total],axis=1)


In [ ]:
check_correlations.head(10)

In [97]:
#problem solving 3 not finished yet